"""create trade_tracking and trade_tracking_txn tables

Revision ID: 6620f3343929
Revises: 467f1684b4ca
Create Date: 2026-06-24 13:09:12.960193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6620f3343929'
down_revision: Union[str, Sequence[str], None] = '467f1684b4ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('TRACKING', 'BUY_ZONE_HIT', 'ACTIVE', 'TARGET_1_HIT', 'STOPLOSS_HIT', 'EXPIRED', 'IGNORED', name='trackingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('buy_zone_min', sa.Float(), nullable=False),
    sa.Column('buy_zone_max', sa.Float(), nullable=False),
    sa.Column('hard_stoploss', sa.Float(), nullable=False),
    sa.Column('target_1', sa.Float(), nullable=False),
    sa.Column('target_2', sa.Float(), nullable=True),
    sa.Column('target_3', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(), nullable=False),
    sa.Column('trade_thesis', sa.String(), nullable=False),
    sa.Column('confirmation_conditions', sa.JSON(), nullable=False),
    sa.Column('post_entry_watchouts', sa.JSON(), nullable=False),
    sa.Column('original_plan_json', sa.JSON(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_tracking_created_at'), 'trade_tracking', ['created_at'], unique=False)
    op.create_index(op.f('ix_trade_tracking_id'), 'trade_tracking', ['id'], unique=False)
    op.create_index(op.f('ix_trade_tracking_status'), 'trade_tracking', ['status'], unique=False)
    op.create_index(op.f('ix_trade_tracking_symbol'), 'trade_tracking', ['symbol'], unique=False)
    op.create_table('trade_tracking_txn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_tracking_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('TRADE_CREATED', 'BUY_ZONE_HIT', 'TARGET_1_HIT', 'STOPLOSS_HIT', 'TRADE_CLOSED', 'EXPIRED', 'IGNORED', name='tradeeventtype'), nullable=False),
    sa.Column('old_status', sa.Enum('TRACKING', 'BUY_ZONE_HIT', 'ACTIVE', 'TARGET_1_HIT', 'STOPLOSS_HIT', 'EXPIRED', 'IGNORED', name='trackingstatus'), nullable=True),
    sa.Column('new_status', sa.Enum('TRACKING', 'BUY_ZONE_HIT', 'ACTIVE', 'TARGET_1_HIT', 'STOPLOSS_HIT', 'EXPIRED', 'IGNORED', name='trackingstatus'), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('telegram_message_id', sa.String(), nullable=True),
    sa.Column('alert_sent', sa.Boolean(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trade_tracking_id'], ['trade_tracking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_tracking_txn_id'), 'trade_tracking_txn', ['id'], unique=False)
    op.create_index(op.f('ix_trade_tracking_txn_trade_tracking_id'), 'trade_tracking_txn', ['trade_tracking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_tracking_txn_trade_tracking_id'), table_name='trade_tracking_txn')
    op.drop_index(op.f('ix_trade_tracking_txn_id'), table_name='trade_tracking_txn')
    op.drop_table('trade_tracking_txn')
    op.drop_index(op.f('ix_trade_tracking_symbol'), table_name='trade_tracking')
    op.drop_index(op.f('ix_trade_tracking_status'), table_name='trade_tracking')
    op.drop_index(op.f('ix_trade_tracking_id'), table_name='trade_tracking')
    op.drop_index(op.f('ix_trade_tracking_created_at'), table_name='trade_tracking')
    op.drop_table('trade_tracking')
    # ### end Alembic commands ###
