"""Add run_batch to TradeTracking

Revision ID: f80d156589bd
Revises: e77f3a77a063
Create Date: 2026-06-29 18:57:15.805390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f80d156589bd'
down_revision: Union[str, Sequence[str], None] = 'e77f3a77a063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_tracking', sa.Column('run_batch', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_tracking', 'run_batch')
    # ### end Alembic commands ###
